version: '3'
services:
  nano:
    build: .
    restart: always
    networks:
      - monitor
    devices:
      - /dev/ttyUSB0:/dev/ttyNANO0
    environment:
      - NANO_SERIAL=/dev/ttyNANO0
      - NANO_BAUD=9600
  influxdb:
    image: influxdb:1.7
    networks:
      - monitor
    volumes:
    - influxdb:/var/lib/influxdb
    ports:
    - 8086:8086

networks:
  monitor:

volumes:
  influxdb: